# TOPICS  target_position_ned_filtered
float32 x           # X Position in NED frame in meters
float32 y           # Y Position in NED frame in meters
float32 z           # Z Position in NED frame in meters
float32 vx          # X Velocity in NED frame in meter / s
float32 vy          # Y Velocity in NED frame in meter / s
float32 vz          # Z Velocity in NED frame in meter / s
float32 var_x       # X Position variance meter^2
float32 var_y       # Y Position variance meter^2
float32 var_z       # Z Position variance meter^2
float32 var_vx      # X Velocity variance (meter/s)^2
float32 var_vy      # Y Velocity variance (meter/s)^2
float32 var_vz      # Z Velocity variance (meter/s)^2
uint8 target_id     # target id
