#!/usr/bin/env bash

set -e

# This script strips the development version of the dronecourse source code from
# solutions and pushes only the student-facing version to a public repository.

# https://github.com/mavlink/mavlink/blob/master/scripts/travis_update_generated_repos.sh#L28-L31
git config --global user.email "dronecourse-bot@epfl.ch"
git config --global user.name "dronecourse-bot"
git config --global credential.helper "store --file=$HOME/.git-credentials"
echo "https://${GH_TOKEN}:@github.com" > $HOME/.git-credentials

STUDENT_REPO_NAME=dronecourse-template
STUDENT_REPO_URL=git@github.com:dronecourse-epfl/${STUDENT_REPO_NAME}.git
FIRMWARE_ROOT=$PWD

make dronecourse_bootstrap
echo $FIRMWARE_ROOT
cd ../
git clone $STUDENT_REPO_URL $STUDENT_REPO_NAME
cd $STUDENT_REPO_NAME
rm -rf *

cp -r $FIRMWARE_ROOT/* .
rm -rf src/dronecourse_bkp
rm -rf src/dronecourse_dev
rm -rf build_*
rm src/.gitignore
find . -type f -name ".git" | xargs rm -rf
find . -type f -name ".gitmodules" | xargs rm -rf
cp $FIRMWARE_ROOT/.gitignore .

# Add CircleCI config for students
mkdir -p .circleci
mv student-config.yml .circleci/.config.yml

git add --all
COMMIT_MESSAGE="Autogenerated code for students"
git commit -m "${COMMIT_MESSAGE}"
git push origin master
